### ISSUE TITLE
Initial increment

### ISSUE THREAD

**Issue by pnkov** [dorantor/mcounter#1]
**Current behavior**
When incrementing counter with memcached key that does not exists, the value sets to initial counter value.

**Expected behavior**
Value setted to initial counter value plus increment step.

**Comment by dorantor** [comment]
Currently it behaves the same way as it is in memcached lib. In some way it seems logical. If you're updating from nothing - next value will be starting one. Such approach makes lib convenient to use, you don't have to check and initialize counter separately. But, from the other side, if you checked values, called `inc()`, and checked `value()` after that you should get initial value incremented by given step.

So your logic also makes sense. First approach that it should be two different inc methods, but I have to think carefully about that, because it's not the only possible solution.

**Comment by dorantor** [comment]
Found a way to support mentioned logic, as it seems more proper. Available since 1.3.0.
